"""
ARC/server/app.py
FastAPI application — wired by openenv init, powered by ARC_environment.py.

Run:
  uvicorn ARC.server.app:app --reload --port 8000

Endpoints (auto-generated by OpenEnv):
  POST /reset       → start new episode
  POST /step        → take one action
  GET  /state       → full simulation state
  GET  /web         → built-in OpenEnv UI
  GET  /schema      → action / observation schemas
  GET  /health      → server health
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from openenv.core.env_server import create_fastapi_app
from models import ARCAction, ARCObservation
from server.ARC_environment import ARCEnvironment


# create_fastapi_app expects a factory callable, not an instance
app = create_fastapi_app(
    env             = ARCEnvironment,   # factory — called per session
    action_cls      = ARCAction,
    observation_cls = ARCObservation,
)



def main():
    """Entry point — strictly callable with no arguments for openenv validate."""
    import uvicorn
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=7860)
    
    args, _ = parser.parse_known_args()
    
    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()