"""
ARCE/server/app.py
FastAPI application - wired by openenv init, powered by ARC_environment.py.

Run:
  uvicorn ARCE.server.app:app --reload --port 7860

Endpoints (auto-generated by OpenEnv):
  POST /reset       -> start new episode
  POST /step        -> take one action
  GET  /state       -> full simulation state
  GET  /web         -> built-in OpenEnv UI
  GET  /schema      -> action / observation schemas
  GET  /health      -> server health
  GET  /            -> Hugging Face Spaces Health Check (Injected)
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from typing import Optional
from pydantic import BaseModel
from openenv.core.env_server import create_fastapi_app
from ARCE.models import ARCAction, ARCObservation, ARCState
from ARCE.server.ARC_environment import ARCEnvironment


# create_fastapi_app expects a factory callable, not an instance
app = create_fastapi_app(
    env             = ARCEnvironment,   # factory - called per session
    action_cls      = ARCAction,
    observation_cls = ARCObservation,
)


class GymResetRequest(BaseModel):
    seed: Optional[int] = None
    difficulty: Optional[str] = None


_gym_env = ARCEnvironment()

# =====================================================================
# HF SPACES FIX: Inject a root path to satisfy platform health probes
# =====================================================================
@app.get("/")
def hf_space_health_check():
    """
    Hugging Face Spaces continuously pings GET / to check if the 
    container is alive. Without this, it gets a 404 and times out.
    """
    return {
        "status": "healthy", 
        "env": "ARCE-India", 
        "message": "Environment is ready for RL training!"
    }


@app.post("/RESET", response_model=ARCObservation)
def gym_like_reset(payload: GymResetRequest | None = None) -> ARCObservation:
    """Gym-like POST reset endpoint for simple clients."""
    payload = payload or GymResetRequest()
    kwargs = {}
    if payload.difficulty:
        kwargs["difficulty"] = payload.difficulty
    return _gym_env.reset(seed=payload.seed, **kwargs)


@app.post("/STEP", response_model=ARCObservation)
def gym_like_step(action: ARCAction) -> ARCObservation:
    """Gym-like POST step endpoint for simple clients."""
    return _gym_env.step(action=action)


@app.post("/STATE", response_model=ARCState)
def gym_like_state() -> ARCState:
    """Gym-like POST state endpoint for simple clients."""
    return _gym_env.state

@app.get("/web")
def web(logs: str = None):
    return {
        "status": "ok",
        "service": "ARCE-India",
        "logs": logs,
        "healthy": True
    }


def main():
    """Entry point - strictly callable with no arguments for openenv validate."""
    import uvicorn
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="0.0.0.0")
    # Defaulting to 7860 as this is the standard port Hugging Face Spaces exposes
    parser.add_argument("--port", type=int, default=7860)
    
    args, _ = parser.parse_known_args()
    
    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()